name: Auto Update Channels

on:
  schedule:
    # Nhóm chạy 3 tiếng một lần (sctv14, sctv19, sctv21)
    - cron: '0 */10 * * *'
    # Nhóm chạy 12 tiếng một lần (các kênh còn lại)
    - cron: '0 */12 * * *'
  workflow_dispatch: # Cho phép bấm chạy thủ công tất cả các kênh

jobs:
  update-link:
    name: cập nhật link
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Tải mã nguồn
      uses: actions/checkout@v4

    - name: Cài đặt Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cài thư viện
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Kiểm tra lịch cron
      id: check-group
      run: |
        UPDATE_TYPE="ALL"
        if [ "${{ github.event_name }}" = "schedule" ]; then
          CRON_TIME="${{ github.event.schedule }}"
          if [ "$CRON_TIME" = "0 */3 * * *" ]; then
            UPDATE_TYPE="FAST"
          elif [ "$CRON_TIME" = "0 */12 * * *" ]; then
            UPDATE_TYPE="SLOW"
          fi
        fi
        echo "UPDATE_TYPE=$UPDATE_TYPE" >> $GITHUB_ENV
        echo "--> Nhóm kênh sẽ được cập nhật lần này: $UPDATE_TYPE"

    - name: Chạy script cập nhật
      env:
        UPDATE_TYPE: ${{ env.UPDATE_TYPE }}
      run: python .github/workflows/auto_update_link_tivi.py

    - name: Lưu thay đổi
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        if [ -n "$(git status --porcelain)" ]; then
          git add tivi.m3u
          git commit -m "[$UPDATE_TYPE]: Đã cập nhật xong"
          git push
        else
          echo "Link hôm nay không đổi so với link cũ."
        fi
