name: Generate Changelog

on:
  push:
    branches: [ main ]
    # Ngăn workflow chạy lại khi file CHANGELOG.md thay đổi
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Thiết lập múi giờ Việt Nam cho môi trường chạy
    env:
      TZ: Asia/Ho_Chi_Minh
      
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Cần fetch-depth: 0 để lấy toàn bộ lịch sử commit
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
          
          # Tự động push code sau khi ghi file
          git-push: true
          
          # Đảm bảo file được tạo đúng tên
          output-file: "CHANGELOG.md" 
          
          # Thêm [skip ci] để tránh kích hoạt workflow vô tận
          git-message: 'nhật ký thay đổi: {version}'
          
          # Tùy chọn: Nếu bạn muốn tạo tag phiên bản luôn thì để là true
          create-summary: true
