name: Generate Changelog

on:
  push:
    branches: [ main ]
    # Ngăn chặn action chạy khi commit có chứa [skip ci] để tránh vòng lặp
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Sử dụng GITHUB_TOKEN mặc định
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
          git-push: true
          output-file: "CHANGELOG.md"
          # Tùy chọn: Nhảy tag phiên bản tự động
          skip-on-empty: false 
          # Giúp tránh vòng lặp bằng cách thêm tag skip ci vào commit message của bot
          git-message: 'chore(release): {version} [skip ci]'
