name: Tự động cập nhật link SCTV 2h/lần

on:
  schedule:
    # Chạy mỗi 2 tiếng (tính theo giờ UTC)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Giúp bạn có thể bấm nút chạy thủ công bất cứ lúc nào trên GitHub

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
    - name: Kiểm tra mã nguồn (Checkout)
      uses: actions/checkout@v4

    - name: Cài đặt Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Chạy script cập nhật link
      run: python link_sctv_update.py

    - name: Kiểm tra thay đổi và Push lên lại Kho lưu trữ
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Kiểm tra xem file tivi.m3u có thay đổi hay không
        if ! git diff --exit-code tivi.m3u; then
          git add tivi.m3u
          git commit -m "Tự động cập nhật link mới [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push
        else
          echo "Không có thay đổi nào về link, bỏ qua commit."
        fi
