name: Tự động cập nhật link SCTV

on:
  schedule:
    - cron: '0 */2 * * *' # Chạy mỗi 2 giờ
  workflow_dispatch:      # Cho phép bấm chạy thủ công

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cần quyền ghi để đẩy file cập nhật lên repo

    steps:
      - name: Lấy mã nguồn từ Repository
        uses: actions/checkout@v4

      - name: Cài đặt Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện cloudscraper
        run: pip install cloudscraper

      - name: Chạy script lấy link và cập nhật
        run: python link_sctv_update.py

      - name: Lưu các file lên Github (Commit & Push)
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Kiểm tra xem có file nào thay đổi không
          git add tivi.m3u file/link_sctv_update.txt
          
          # Chỉ commit nếu có sự thay đổi thực sự
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: Cập nhật link SCTV mới"
          git push
