name: Auto Update SCTV Link

on:
  schedule:
    - cron: '0 */2 * * *' # Đã đổi thành chạy mỗi 2 tiếng cho kịp thời gian link hết hạn
  workflow_dispatch: # Giúp bạn có thể bấm nút chạy thủ công trên GitHub để test ngay

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cấp quyền cho bot ghi/push file lên repo

    steps:
    - name: Checkout mã nguồn
      uses: actions/checkout@v4

    - name: Cài đặt Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24 # Đã nâng lên bản 24 mới nhất theo thông báo của GitHub

    - name: Chạy script cập nhật link
      run: node link_sctv_update.js # Đảm bảo file JS ngoài thư mục gốc cũng tên là link_sctv_update.js

    - name: Commit và Push nếu có thay đổi
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git diff --quiet || (git add . && git commit -m "Bot: Cập nhật link SCTV mới [$(date +'%Y-%m-%d %H:%M:%S')]" && git push)
