name: Extract IPTV Link to Text File With M3U8 Extension

on:
  schedule:
    - cron: '0 */2 * * *' # Tự động chạy mỗi 2 tiếng một lần
  workflow_dispatch: # Nút bấm chạy bằng tay bất cứ lúc nào

jobs:
  extract-link:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Run JavaScript Extract Link
      run: node extract.js

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        git add link_sctv.txt
        git commit -m "Bypass 403 và cập nhật link m3u8" || echo "Không có thay đổi"
        git push
